# Example: Tokyo (dest_id -246227, matching the sample search URL you shared:
# .../searchresults.html?dest_id=-246227&dest_type=city...). Replace/extend
# this with your actual destinations and sponsored partners.
SPONSORED_MOCK_HOTELS: list[dict] = [
    {
        "dest_id": "-246227",
        "hotel_id": "sponsored-tokyo-001",
        "name": "The Ginza Grand Hotel & Spa",
        "address": "5-4-1 Ginza",
        "city": "Chuo City",
        "latitude": 35.6717,
        "longitude": 139.7650,
        "star_rating": 5,
        "price": 245.00,
        "rating": 9.1,
        "image_url": "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
        "free_cancellation": True,
        "no_prepayment": True,
        "is_sold_out": False,
        "room_name": None,
    },
    {
        "dest_id": "-246227",
        "hotel_id": "sponsored-tokyo-002",
        "name": "Shinjuku Skyline Suites",
        "address": "2-1-1 Nishi-Shinjuku",
        "city": "Shinjuku City",
        "latitude": 35.6896,
        "longitude": 139.6917,
        "star_rating": 4,
        "price": 168.50,
        "rating": 8.7,
        "image_url": "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800",
        "free_cancellation": True,
        "no_prepayment": False,
        "is_sold_out": False,
        "room_name": None,
    },
    {
        "dest_id": "-246227",
        "hotel_id": "sponsored-tokyo-003",
        "name": "Asakusa Riverside Ryokan",
        "address": "1-3-2 Asakusa",
        "city": "Taito City",
        "latitude": 35.7118,
        "longitude": 139.7966,
        "star_rating": 4,
        "price": 132.00,
        "rating": 9.3,
        "image_url": "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800",
        "free_cancellation": True,
        "no_prepayment": True,
        "is_sold_out": False,
        "room_name": None,
    },
]